import Head from "next/head";
import BackToTop from "../componentCommon/button/BackToTop";
import Footer from "../componentCommon/footer";
import Header from "../componentCommon/header";
import MobileNavigation from "../componentCommon/header/MobileNavigation";
import { Providers } from "./providers";

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Providers>
          <div id="wrapper">
            <div id="page" className="clearfix">
              <Header />
              <MobileNavigation />
              {children}
              <Footer />
            </div>
          </div>
          <BackToTop />
        </Providers>
      </main>
    </>
  );
}
